package com.gcloud.goods.domain;

import java.util.Date;

public class GoodsBrand {
    /**
     * 商品类目主键 <p/>
     * This field corresponds to the database column tb_goods_brand.id
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private Long id;

    /**
     * 类目ID <p/>
     * This field corresponds to the database column tb_goods_brand.brand_id
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private Long brandId;

    /**
     * 类目名称 <p/>
     * This field corresponds to the database column tb_goods_brand.brand_name
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private String brandName;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_brand.status
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private Byte status;

    /**
     * 平台信息 <p/>
     * This field corresponds to the database column tb_goods_brand.platform
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_brand.remark
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_brand.created
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_brand.modified
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_brand.enable_status
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 商品类目主键 <p/>
     * This method returns the value of the database column tb_goods_brand.id
     *
     * @return the value of tb_goods_brand.id
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 商品类目主键 <p/>
     * This method sets the value of the database column tb_goods_brand.id
     *
     * @param id the value for tb_goods_brand.id
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 类目ID <p/>
     * This method returns the value of the database column tb_goods_brand.brand_id
     *
     * @return the value of tb_goods_brand.brand_id
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * 类目ID <p/>
     * This method sets the value of the database column tb_goods_brand.brand_id
     *
     * @param brandId the value for tb_goods_brand.brand_id
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * 类目名称 <p/>
     * This method returns the value of the database column tb_goods_brand.brand_name
     *
     * @return the value of tb_goods_brand.brand_name
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * 类目名称 <p/>
     * This method sets the value of the database column tb_goods_brand.brand_name
     *
     * @param brandName the value for tb_goods_brand.brand_name
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_brand.status
     *
     * @return the value of tb_goods_brand.status
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_brand.status
     *
     * @param status the value for tb_goods_brand.status
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息 <p/>
     * This method returns the value of the database column tb_goods_brand.platform
     *
     * @return the value of tb_goods_brand.platform
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息 <p/>
     * This method sets the value of the database column tb_goods_brand.platform
     *
     * @param platform the value for tb_goods_brand.platform
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_brand.remark
     *
     * @return the value of tb_goods_brand.remark
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_brand.remark
     *
     * @param remark the value for tb_goods_brand.remark
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_brand.created
     *
     * @return the value of tb_goods_brand.created
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_brand.created
     *
     * @param created the value for tb_goods_brand.created
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_brand.modified
     *
     * @return the value of tb_goods_brand.modified
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_brand.modified
     *
     * @param modified the value for tb_goods_brand.modified
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_brand.enable_status
     *
     * @return the value of tb_goods_brand.enable_status
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_brand.enable_status
     *
     * @param enableStatus the value for tb_goods_brand.enable_status
     *
     * @mbggenerated Sun Aug 14 11:24:31 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}