package com.gcloud.goods.domain;

import java.util.Date;

public class GoodsSku {
    /**
     * 商品SKU <p/>
     * This field corresponds to the database column tb_goods_sku.goods_sku
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long goodsSku;

    /**
     * 商品SKU表主键 <p/>
     * This field corresponds to the database column tb_goods_sku.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long id;

    /**
     * 公司ID <p/>
     * This field corresponds to the database column tb_goods_sku.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long companyId;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_sku.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long storeId;

    /**
     * 商品SPU <p/>
     * This field corresponds to the database column tb_goods_sku.goods_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long goodsSpu;

    /**
     * 商品SPU(外部系统) <p/>
     * This field corresponds to the database column tb_goods_sku.goods_out_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String goodsOutSpu;

    /**
     * 商品外部系统ID <p/>
     * This field corresponds to the database column tb_goods_sku.goods_out_sku
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String goodsOutSku;

    /**
     * 商品名称 <p/>
     * This field corresponds to the database column tb_goods_sku.goods_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String goodsName;

    /**
     * 商品简称 <p/>
     * This field corresponds to the database column tb_goods_sku.short_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String shortName;

    /**
     * 条形码 <p/>
     * This field corresponds to the database column tb_goods_sku.barcode
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String barcode;

    /**
     * 商品图片 <p/>
     * This field corresponds to the database column tb_goods_sku.pic_path
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String picPath;

    /**
     * 商品属性 <p/>
     * This field corresponds to the database column tb_goods_sku.props_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String propsName;

    /**
     * 成本价 <p/>
     * This field corresponds to the database column tb_goods_sku.cost_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Double costPrice;

    /**
     * 销售价 <p/>
     * This field corresponds to the database column tb_goods_sku.sell_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Double sellPrice;

    /**
     * 零售价 <p/>
     * This field corresponds to the database column tb_goods_sku.retail_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Double retailPrice;

    /**
     * 会员价 <p/>
     * This field corresponds to the database column tb_goods_sku.member_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Double memberPrice;

    /**
     * 特价 <p/>
     * This field corresponds to the database column tb_goods_sku.special_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Double specialPrice;

    /**
     * 重量 <p/>
     * This field corresponds to the database column tb_goods_sku.weight
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Double weight;

    /**
     * 单位 <p/>
     * This field corresponds to the database column tb_goods_sku.unit
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String unit;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_sku.remark
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 商品SKU <p/>
     * This method returns the value of the database column tb_goods_sku.goods_sku
     *
     * @return the value of tb_goods_sku.goods_sku
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getGoodsSku() {
        return goodsSku;
    }

    /**
     * 商品SKU <p/>
     * This method sets the value of the database column tb_goods_sku.goods_sku
     *
     * @param goodsSku the value for tb_goods_sku.goods_sku
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsSku(Long goodsSku) {
        this.goodsSku = goodsSku;
    }

    /**
     * 商品SKU表主键 <p/>
     * This method returns the value of the database column tb_goods_sku.id
     *
     * @return the value of tb_goods_sku.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 商品SKU表主键 <p/>
     * This method sets the value of the database column tb_goods_sku.id
     *
     * @param id the value for tb_goods_sku.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 公司ID <p/>
     * This method returns the value of the database column tb_goods_sku.company_id
     *
     * @return the value of tb_goods_sku.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * 公司ID <p/>
     * This method sets the value of the database column tb_goods_sku.company_id
     *
     * @param companyId the value for tb_goods_sku.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_sku.store_id
     *
     * @return the value of tb_goods_sku.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_sku.store_id
     *
     * @param storeId the value for tb_goods_sku.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * 商品SPU <p/>
     * This method returns the value of the database column tb_goods_sku.goods_spu
     *
     * @return the value of tb_goods_sku.goods_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getGoodsSpu() {
        return goodsSpu;
    }

    /**
     * 商品SPU <p/>
     * This method sets the value of the database column tb_goods_sku.goods_spu
     *
     * @param goodsSpu the value for tb_goods_sku.goods_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsSpu(Long goodsSpu) {
        this.goodsSpu = goodsSpu;
    }

    /**
     * 商品SPU(外部系统) <p/>
     * This method returns the value of the database column tb_goods_sku.goods_out_spu
     *
     * @return the value of tb_goods_sku.goods_out_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getGoodsOutSpu() {
        return goodsOutSpu;
    }

    /**
     * 商品SPU(外部系统) <p/>
     * This method sets the value of the database column tb_goods_sku.goods_out_spu
     *
     * @param goodsOutSpu the value for tb_goods_sku.goods_out_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsOutSpu(String goodsOutSpu) {
        this.goodsOutSpu = goodsOutSpu == null ? null : goodsOutSpu.trim();
    }

    /**
     * 商品外部系统ID <p/>
     * This method returns the value of the database column tb_goods_sku.goods_out_sku
     *
     * @return the value of tb_goods_sku.goods_out_sku
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getGoodsOutSku() {
        return goodsOutSku;
    }

    /**
     * 商品外部系统ID <p/>
     * This method sets the value of the database column tb_goods_sku.goods_out_sku
     *
     * @param goodsOutSku the value for tb_goods_sku.goods_out_sku
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsOutSku(String goodsOutSku) {
        this.goodsOutSku = goodsOutSku == null ? null : goodsOutSku.trim();
    }

    /**
     * 商品名称 <p/>
     * This method returns the value of the database column tb_goods_sku.goods_name
     *
     * @return the value of tb_goods_sku.goods_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * 商品名称 <p/>
     * This method sets the value of the database column tb_goods_sku.goods_name
     *
     * @param goodsName the value for tb_goods_sku.goods_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * 商品简称 <p/>
     * This method returns the value of the database column tb_goods_sku.short_name
     *
     * @return the value of tb_goods_sku.short_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * 商品简称 <p/>
     * This method sets the value of the database column tb_goods_sku.short_name
     *
     * @param shortName the value for tb_goods_sku.short_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * 条形码 <p/>
     * This method returns the value of the database column tb_goods_sku.barcode
     *
     * @return the value of tb_goods_sku.barcode
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * 条形码 <p/>
     * This method sets the value of the database column tb_goods_sku.barcode
     *
     * @param barcode the value for tb_goods_sku.barcode
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * 商品图片 <p/>
     * This method returns the value of the database column tb_goods_sku.pic_path
     *
     * @return the value of tb_goods_sku.pic_path
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * 商品图片 <p/>
     * This method sets the value of the database column tb_goods_sku.pic_path
     *
     * @param picPath the value for tb_goods_sku.pic_path
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * 商品属性 <p/>
     * This method returns the value of the database column tb_goods_sku.props_name
     *
     * @return the value of tb_goods_sku.props_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getPropsName() {
        return propsName;
    }

    /**
     * 商品属性 <p/>
     * This method sets the value of the database column tb_goods_sku.props_name
     *
     * @param propsName the value for tb_goods_sku.props_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setPropsName(String propsName) {
        this.propsName = propsName == null ? null : propsName.trim();
    }

    /**
     * 成本价 <p/>
     * This method returns the value of the database column tb_goods_sku.cost_price
     *
     * @return the value of tb_goods_sku.cost_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * 成本价 <p/>
     * This method sets the value of the database column tb_goods_sku.cost_price
     *
     * @param costPrice the value for tb_goods_sku.cost_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * 销售价 <p/>
     * This method returns the value of the database column tb_goods_sku.sell_price
     *
     * @return the value of tb_goods_sku.sell_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Double getSellPrice() {
        return sellPrice;
    }

    /**
     * 销售价 <p/>
     * This method sets the value of the database column tb_goods_sku.sell_price
     *
     * @param sellPrice the value for tb_goods_sku.sell_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setSellPrice(Double sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * 零售价 <p/>
     * This method returns the value of the database column tb_goods_sku.retail_price
     *
     * @return the value of tb_goods_sku.retail_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Double getRetailPrice() {
        return retailPrice;
    }

    /**
     * 零售价 <p/>
     * This method sets the value of the database column tb_goods_sku.retail_price
     *
     * @param retailPrice the value for tb_goods_sku.retail_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setRetailPrice(Double retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * 会员价 <p/>
     * This method returns the value of the database column tb_goods_sku.member_price
     *
     * @return the value of tb_goods_sku.member_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Double getMemberPrice() {
        return memberPrice;
    }

    /**
     * 会员价 <p/>
     * This method sets the value of the database column tb_goods_sku.member_price
     *
     * @param memberPrice the value for tb_goods_sku.member_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setMemberPrice(Double memberPrice) {
        this.memberPrice = memberPrice;
    }

    /**
     * 特价 <p/>
     * This method returns the value of the database column tb_goods_sku.special_price
     *
     * @return the value of tb_goods_sku.special_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Double getSpecialPrice() {
        return specialPrice;
    }

    /**
     * 特价 <p/>
     * This method sets the value of the database column tb_goods_sku.special_price
     *
     * @param specialPrice the value for tb_goods_sku.special_price
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setSpecialPrice(Double specialPrice) {
        this.specialPrice = specialPrice;
    }

    /**
     * 重量 <p/>
     * This method returns the value of the database column tb_goods_sku.weight
     *
     * @return the value of tb_goods_sku.weight
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * 重量 <p/>
     * This method sets the value of the database column tb_goods_sku.weight
     *
     * @param weight the value for tb_goods_sku.weight
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * 单位 <p/>
     * This method returns the value of the database column tb_goods_sku.unit
     *
     * @return the value of tb_goods_sku.unit
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * 单位 <p/>
     * This method sets the value of the database column tb_goods_sku.unit
     *
     * @param unit the value for tb_goods_sku.unit
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_sku.remark
     *
     * @return the value of tb_goods_sku.remark
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_sku.remark
     *
     * @param remark the value for tb_goods_sku.remark
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.created
     *
     * @return the value of tb_goods_sku.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.created
     *
     * @param created the value for tb_goods_sku.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.modified
     *
     * @return the value of tb_goods_sku.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.modified
     *
     * @param modified the value for tb_goods_sku.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.enable_status
     *
     * @return the value of tb_goods_sku.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.enable_status
     *
     * @param enableStatus the value for tb_goods_sku.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}