package com.gcloud.goods.domain;

import java.util.Date;

public class GoodsStock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_stock.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long id;

    /**
     * 公司ID <p/>
     * This field corresponds to the database column tb_goods_stock.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long companyId;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_stock.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long storeId;

    /**
     * 商品SKU <p/>
     * This field corresponds to the database column tb_goods_stock.item_sku_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long itemSkuId;

    /**
     * 仓库ID <p/>
     * This field corresponds to the database column tb_goods_stock.warehouse_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long warehouseId;

    /**
     * 实际库存 <p/>
     * This field corresponds to the database column tb_goods_stock.actual_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long actualStock;

    /**
     * 闲置库存 <p/>
     * This field corresponds to the database column tb_goods_stock.available_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long availableStock;

    /**
     * 锁定库存 <p/>
     * This field corresponds to the database column tb_goods_stock.lock_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long lockStock;

    /**
     * 缺陷库存 <p/>
     * This field corresponds to the database column tb_goods_stock.defective_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long defectiveStock;

    /**
     * 警告库存 <p/>
     * This field corresponds to the database column tb_goods_stock.alarm_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long alarmStock;

    /**
     * 销售数量 <p/>
     * This field corresponds to the database column tb_goods_stock.quantity
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_stock.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_stock.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_stock.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Boolean enableStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_stock.id
     *
     * @return the value of tb_goods_stock.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_stock.id
     *
     * @param id the value for tb_goods_stock.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 公司ID <p/>
     * This method returns the value of the database column tb_goods_stock.company_id
     *
     * @return the value of tb_goods_stock.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * 公司ID <p/>
     * This method sets the value of the database column tb_goods_stock.company_id
     *
     * @param companyId the value for tb_goods_stock.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_stock.store_id
     *
     * @return the value of tb_goods_stock.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_stock.store_id
     *
     * @param storeId the value for tb_goods_stock.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * 商品SKU <p/>
     * This method returns the value of the database column tb_goods_stock.item_sku_id
     *
     * @return the value of tb_goods_stock.item_sku_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getItemSkuId() {
        return itemSkuId;
    }

    /**
     * 商品SKU <p/>
     * This method sets the value of the database column tb_goods_stock.item_sku_id
     *
     * @param itemSkuId the value for tb_goods_stock.item_sku_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setItemSkuId(Long itemSkuId) {
        this.itemSkuId = itemSkuId;
    }

    /**
     * 仓库ID <p/>
     * This method returns the value of the database column tb_goods_stock.warehouse_id
     *
     * @return the value of tb_goods_stock.warehouse_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * 仓库ID <p/>
     * This method sets the value of the database column tb_goods_stock.warehouse_id
     *
     * @param warehouseId the value for tb_goods_stock.warehouse_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * 实际库存 <p/>
     * This method returns the value of the database column tb_goods_stock.actual_stock
     *
     * @return the value of tb_goods_stock.actual_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getActualStock() {
        return actualStock;
    }

    /**
     * 实际库存 <p/>
     * This method sets the value of the database column tb_goods_stock.actual_stock
     *
     * @param actualStock the value for tb_goods_stock.actual_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setActualStock(Long actualStock) {
        this.actualStock = actualStock;
    }

    /**
     * 闲置库存 <p/>
     * This method returns the value of the database column tb_goods_stock.available_stock
     *
     * @return the value of tb_goods_stock.available_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getAvailableStock() {
        return availableStock;
    }

    /**
     * 闲置库存 <p/>
     * This method sets the value of the database column tb_goods_stock.available_stock
     *
     * @param availableStock the value for tb_goods_stock.available_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setAvailableStock(Long availableStock) {
        this.availableStock = availableStock;
    }

    /**
     * 锁定库存 <p/>
     * This method returns the value of the database column tb_goods_stock.lock_stock
     *
     * @return the value of tb_goods_stock.lock_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getLockStock() {
        return lockStock;
    }

    /**
     * 锁定库存 <p/>
     * This method sets the value of the database column tb_goods_stock.lock_stock
     *
     * @param lockStock the value for tb_goods_stock.lock_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setLockStock(Long lockStock) {
        this.lockStock = lockStock;
    }

    /**
     * 缺陷库存 <p/>
     * This method returns the value of the database column tb_goods_stock.defective_stock
     *
     * @return the value of tb_goods_stock.defective_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getDefectiveStock() {
        return defectiveStock;
    }

    /**
     * 缺陷库存 <p/>
     * This method sets the value of the database column tb_goods_stock.defective_stock
     *
     * @param defectiveStock the value for tb_goods_stock.defective_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setDefectiveStock(Long defectiveStock) {
        this.defectiveStock = defectiveStock;
    }

    /**
     * 警告库存 <p/>
     * This method returns the value of the database column tb_goods_stock.alarm_stock
     *
     * @return the value of tb_goods_stock.alarm_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getAlarmStock() {
        return alarmStock;
    }

    /**
     * 警告库存 <p/>
     * This method sets the value of the database column tb_goods_stock.alarm_stock
     *
     * @param alarmStock the value for tb_goods_stock.alarm_stock
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setAlarmStock(Long alarmStock) {
        this.alarmStock = alarmStock;
    }

    /**
     * 销售数量 <p/>
     * This method returns the value of the database column tb_goods_stock.quantity
     *
     * @return the value of tb_goods_stock.quantity
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * 销售数量 <p/>
     * This method sets the value of the database column tb_goods_stock.quantity
     *
     * @param quantity the value for tb_goods_stock.quantity
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_stock.created
     *
     * @return the value of tb_goods_stock.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_stock.created
     *
     * @param created the value for tb_goods_stock.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_stock.modified
     *
     * @return the value of tb_goods_stock.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_stock.modified
     *
     * @param modified the value for tb_goods_stock.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_stock.enable_status
     *
     * @return the value of tb_goods_stock.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_stock.enable_status
     *
     * @param enableStatus the value for tb_goods_stock.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}