package com.gcloud.goods.domain;

import java.util.Date;

public class GoodsCategory {
    /**
     * 主键 <p/>
     * This field corresponds to the database column tb_goods_category.id
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Long id;

    /**
     * 类目ID <p/>
     * This field corresponds to the database column tb_goods_category.cat_id
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Long catId;

    /**
     * 类目名称 <p/>
     * This field corresponds to the database column tb_goods_category.cat_name
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private String catName;

    /**
     * 父级类目ID <p/>
     * This field corresponds to the database column tb_goods_category.parent_cid
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Long parentCid;

    /**
     * 该类目是否为父类目(即：该类目是否还有子类目) <p/>
     * This field corresponds to the database column tb_goods_category.is_parent
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Byte isParent;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_category.status
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Byte status;

    /**
     * 平台信息 <p/>
     * This field corresponds to the database column tb_goods_category.platform
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_category.remark
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_category.created
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_category.modified
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Date modified;

    /**
     * 0否 1是 <p/>
     * This field corresponds to the database column tb_goods_category.enable_status
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 主键 <p/>
     * This method returns the value of the database column tb_goods_category.id
     *
     * @return the value of tb_goods_category.id
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 主键 <p/>
     * This method sets the value of the database column tb_goods_category.id
     *
     * @param id the value for tb_goods_category.id
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 类目ID <p/>
     * This method returns the value of the database column tb_goods_category.cat_id
     *
     * @return the value of tb_goods_category.cat_id
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Long getCatId() {
        return catId;
    }

    /**
     * 类目ID <p/>
     * This method sets the value of the database column tb_goods_category.cat_id
     *
     * @param catId the value for tb_goods_category.cat_id
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setCatId(Long catId) {
        this.catId = catId;
    }

    /**
     * 类目名称 <p/>
     * This method returns the value of the database column tb_goods_category.cat_name
     *
     * @return the value of tb_goods_category.cat_name
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public String getCatName() {
        return catName;
    }

    /**
     * 类目名称 <p/>
     * This method sets the value of the database column tb_goods_category.cat_name
     *
     * @param catName the value for tb_goods_category.cat_name
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * 父级类目ID <p/>
     * This method returns the value of the database column tb_goods_category.parent_cid
     *
     * @return the value of tb_goods_category.parent_cid
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Long getParentCid() {
        return parentCid;
    }

    /**
     * 父级类目ID <p/>
     * This method sets the value of the database column tb_goods_category.parent_cid
     *
     * @param parentCid the value for tb_goods_category.parent_cid
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setParentCid(Long parentCid) {
        this.parentCid = parentCid;
    }

    /**
     * 该类目是否为父类目(即：该类目是否还有子类目) <p/>
     * This method returns the value of the database column tb_goods_category.is_parent
     *
     * @return the value of tb_goods_category.is_parent
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Byte getIsParent() {
        return isParent;
    }

    /**
     * 该类目是否为父类目(即：该类目是否还有子类目) <p/>
     * This method sets the value of the database column tb_goods_category.is_parent
     *
     * @param isParent the value for tb_goods_category.is_parent
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setIsParent(Byte isParent) {
        this.isParent = isParent;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_category.status
     *
     * @return the value of tb_goods_category.status
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_category.status
     *
     * @param status the value for tb_goods_category.status
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 平台信息 <p/>
     * This method returns the value of the database column tb_goods_category.platform
     *
     * @return the value of tb_goods_category.platform
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息 <p/>
     * This method sets the value of the database column tb_goods_category.platform
     *
     * @param platform the value for tb_goods_category.platform
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_category.remark
     *
     * @return the value of tb_goods_category.remark
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_category.remark
     *
     * @param remark the value for tb_goods_category.remark
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_category.created
     *
     * @return the value of tb_goods_category.created
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_category.created
     *
     * @param created the value for tb_goods_category.created
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_category.modified
     *
     * @return the value of tb_goods_category.modified
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_category.modified
     *
     * @param modified the value for tb_goods_category.modified
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * 0否 1是 <p/>
     * This method returns the value of the database column tb_goods_category.enable_status
     *
     * @return the value of tb_goods_category.enable_status
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * 0否 1是 <p/>
     * This method sets the value of the database column tb_goods_category.enable_status
     *
     * @param enableStatus the value for tb_goods_category.enable_status
     *
     * @mbggenerated Mon Aug 15 18:23:50 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}