package com.gcloud.goods.domain;

import java.util.Date;

public class GoodsSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.sku_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.taobao_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long taobaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.properties_name
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String propertiesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.num_iid
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.short_title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String shortTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.market
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String market;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.factory
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String factory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.goods_allocation
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String goodsAllocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.actual_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long actualStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.available_in_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long availableInStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.lock_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long lockStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.defective_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long defectiveStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.alarm_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long alarmStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.cost_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.weight
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.barcode
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.created
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.modified
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.enable_status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.pic_path
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String picPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.outer_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String outerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.num
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.alarm
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Integer alarm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.remark
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.cat_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private String catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.sys_sku_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long sysSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.sku_warehouse_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Long skuWarehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_sku.status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.sku_id
     *
     * @return the value of tb_goods_sku.sku_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.sku_id
     *
     * @param skuId the value for tb_goods_sku.sku_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.taobao_id
     *
     * @return the value of tb_goods_sku.taobao_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getTaobaoId() {
        return taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.taobao_id
     *
     * @param taobaoId the value for tb_goods_sku.taobao_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setTaobaoId(Long taobaoId) {
        this.taobaoId = taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.properties_name
     *
     * @return the value of tb_goods_sku.properties_name
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getPropertiesName() {
        return propertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.properties_name
     *
     * @param propertiesName the value for tb_goods_sku.properties_name
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPropertiesName(String propertiesName) {
        this.propertiesName = propertiesName == null ? null : propertiesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.num_iid
     *
     * @return the value of tb_goods_sku.num_iid
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.num_iid
     *
     * @param numIid the value for tb_goods_sku.num_iid
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.short_title
     *
     * @return the value of tb_goods_sku.short_title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.short_title
     *
     * @param shortTitle the value for tb_goods_sku.short_title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle == null ? null : shortTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.market
     *
     * @return the value of tb_goods_sku.market
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.market
     *
     * @param market the value for tb_goods_sku.market
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.factory
     *
     * @return the value of tb_goods_sku.factory
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.factory
     *
     * @param factory the value for tb_goods_sku.factory
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.goods_allocation
     *
     * @return the value of tb_goods_sku.goods_allocation
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getGoodsAllocation() {
        return goodsAllocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.goods_allocation
     *
     * @param goodsAllocation the value for tb_goods_sku.goods_allocation
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setGoodsAllocation(String goodsAllocation) {
        this.goodsAllocation = goodsAllocation == null ? null : goodsAllocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.actual_stock
     *
     * @return the value of tb_goods_sku.actual_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getActualStock() {
        return actualStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.actual_stock
     *
     * @param actualStock the value for tb_goods_sku.actual_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setActualStock(Long actualStock) {
        this.actualStock = actualStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.available_in_stock
     *
     * @return the value of tb_goods_sku.available_in_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getAvailableInStock() {
        return availableInStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.available_in_stock
     *
     * @param availableInStock the value for tb_goods_sku.available_in_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAvailableInStock(Long availableInStock) {
        this.availableInStock = availableInStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.lock_stock
     *
     * @return the value of tb_goods_sku.lock_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getLockStock() {
        return lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.lock_stock
     *
     * @param lockStock the value for tb_goods_sku.lock_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setLockStock(Long lockStock) {
        this.lockStock = lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.defective_stock
     *
     * @return the value of tb_goods_sku.defective_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getDefectiveStock() {
        return defectiveStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.defective_stock
     *
     * @param defectiveStock the value for tb_goods_sku.defective_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setDefectiveStock(Long defectiveStock) {
        this.defectiveStock = defectiveStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.alarm_stock
     *
     * @return the value of tb_goods_sku.alarm_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getAlarmStock() {
        return alarmStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.alarm_stock
     *
     * @param alarmStock the value for tb_goods_sku.alarm_stock
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAlarmStock(Long alarmStock) {
        this.alarmStock = alarmStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.cost_price
     *
     * @return the value of tb_goods_sku.cost_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.cost_price
     *
     * @param costPrice the value for tb_goods_sku.cost_price
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.weight
     *
     * @return the value of tb_goods_sku.weight
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.weight
     *
     * @param weight the value for tb_goods_sku.weight
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.barcode
     *
     * @return the value of tb_goods_sku.barcode
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.barcode
     *
     * @param barcode the value for tb_goods_sku.barcode
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.created
     *
     * @return the value of tb_goods_sku.created
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.created
     *
     * @param created the value for tb_goods_sku.created
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.modified
     *
     * @return the value of tb_goods_sku.modified
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.modified
     *
     * @param modified the value for tb_goods_sku.modified
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.enable_status
     *
     * @return the value of tb_goods_sku.enable_status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.enable_status
     *
     * @param enableStatus the value for tb_goods_sku.enable_status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.pic_path
     *
     * @return the value of tb_goods_sku.pic_path
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.pic_path
     *
     * @param picPath the value for tb_goods_sku.pic_path
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.title
     *
     * @return the value of tb_goods_sku.title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.title
     *
     * @param title the value for tb_goods_sku.title
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.outer_id
     *
     * @return the value of tb_goods_sku.outer_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.outer_id
     *
     * @param outerId the value for tb_goods_sku.outer_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setOuterId(String outerId) {
        this.outerId = outerId == null ? null : outerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.num
     *
     * @return the value of tb_goods_sku.num
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.num
     *
     * @param num the value for tb_goods_sku.num
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.alarm
     *
     * @return the value of tb_goods_sku.alarm
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Integer getAlarm() {
        return alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.alarm
     *
     * @param alarm the value for tb_goods_sku.alarm
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setAlarm(Integer alarm) {
        this.alarm = alarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.remark
     *
     * @return the value of tb_goods_sku.remark
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.remark
     *
     * @param remark the value for tb_goods_sku.remark
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.type
     *
     * @return the value of tb_goods_sku.type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.type
     *
     * @param type the value for tb_goods_sku.type
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.cat_id
     *
     * @return the value of tb_goods_sku.cat_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public String getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.cat_id
     *
     * @param catId the value for tb_goods_sku.cat_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setCatId(String catId) {
        this.catId = catId == null ? null : catId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.sys_sku_id
     *
     * @return the value of tb_goods_sku.sys_sku_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getSysSkuId() {
        return sysSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.sys_sku_id
     *
     * @param sysSkuId the value for tb_goods_sku.sys_sku_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setSysSkuId(Long sysSkuId) {
        this.sysSkuId = sysSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.sku_warehouse_id
     *
     * @return the value of tb_goods_sku.sku_warehouse_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Long getSkuWarehouseId() {
        return skuWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.sku_warehouse_id
     *
     * @param skuWarehouseId the value for tb_goods_sku.sku_warehouse_id
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setSkuWarehouseId(Long skuWarehouseId) {
        this.skuWarehouseId = skuWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_sku.status
     *
     * @return the value of tb_goods_sku.status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_sku.status
     *
     * @param status the value for tb_goods_sku.status
     *
     * @mbggenerated Thu Aug 11 14:24:39 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}