package com.gcloud.goods.domain;

import java.util.Date;

public class GoodsSpu {
    /**
     * 商品SPU <p/>
     * This field corresponds to the database column tb_goods_spu.goods_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long goodsSpu;

    /**
     * 商品SPU表主键 <p/>
     * This field corresponds to the database column tb_goods_spu.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long id;

    /**
     * 公司ID <p/>
     * This field corresponds to the database column tb_goods_spu.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long companyId;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_goods_spu.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long storeId;

    /**
     * 商品名称 <p/>
     * This field corresponds to the database column tb_goods_spu.goods_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String goodsName;

    /**
     * 商品简称 <p/>
     * This field corresponds to the database column tb_goods_spu.short_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String shortName;

    /**
     * 条形码 <p/>
     * This field corresponds to the database column tb_goods_spu.barcode
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String barcode;

    /**
     * 商品图片 <p/>
     * This field corresponds to the database column tb_goods_spu.pic_path
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String picPath;

    /**
     * 商品SPU(外部系统) <p/>
     * This field corresponds to the database column tb_goods_spu.goods_out_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String goodsOutSpu;

    /**
     * 商品类目 <p/>
     * This field corresponds to the database column tb_goods_spu.cat_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String catId;

    /**
     * 商品品牌 <p/>
     * This field corresponds to the database column tb_goods_spu.brand
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String brand;

    /**
     * 商品属性 <p/>
     * This field corresponds to the database column tb_goods_spu.props_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String propsName;

    /**
     * 商品属性别名 <p/>
     * This field corresponds to the database column tb_goods_spu.props_alias
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String propsAlias;

    /**
     * 销售属性 <p/>
     * This field corresponds to the database column tb_goods_spu.sale_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String saleProps;

    /**
     * 商品属性(非关键) <p/>
     * This field corresponds to the database column tb_goods_spu.binds_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String bindsProps;

    /**
     * 商品属性(用户自定义) <p/>
     * This field corresponds to the database column tb_goods_spu.customer_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String customerProps;

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This field corresponds to the database column tb_goods_spu.status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Byte status;

    /**
     * 是否在线销售 0否 1是 <p/>
     * This field corresponds to the database column tb_goods_spu.on_sale
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Byte onSale;

    /**
     * 平台信息 <p/>
     * This field corresponds to the database column tb_goods_spu.platform
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String platform;

    /**
     * 备注 <p/>
     * This field corresponds to the database column tb_goods_spu.remark
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods_spu.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Boolean enableStatus;

    /**
     * 商品SPU <p/>
     * This method returns the value of the database column tb_goods_spu.goods_spu
     *
     * @return the value of tb_goods_spu.goods_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getGoodsSpu() {
        return goodsSpu;
    }

    /**
     * 商品SPU <p/>
     * This method sets the value of the database column tb_goods_spu.goods_spu
     *
     * @param goodsSpu the value for tb_goods_spu.goods_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsSpu(Long goodsSpu) {
        this.goodsSpu = goodsSpu;
    }

    /**
     * 商品SPU表主键 <p/>
     * This method returns the value of the database column tb_goods_spu.id
     *
     * @return the value of tb_goods_spu.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * 商品SPU表主键 <p/>
     * This method sets the value of the database column tb_goods_spu.id
     *
     * @param id the value for tb_goods_spu.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 公司ID <p/>
     * This method returns the value of the database column tb_goods_spu.company_id
     *
     * @return the value of tb_goods_spu.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * 公司ID <p/>
     * This method sets the value of the database column tb_goods_spu.company_id
     *
     * @param companyId the value for tb_goods_spu.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_goods_spu.store_id
     *
     * @return the value of tb_goods_spu.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_goods_spu.store_id
     *
     * @param storeId the value for tb_goods_spu.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * 商品名称 <p/>
     * This method returns the value of the database column tb_goods_spu.goods_name
     *
     * @return the value of tb_goods_spu.goods_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * 商品名称 <p/>
     * This method sets the value of the database column tb_goods_spu.goods_name
     *
     * @param goodsName the value for tb_goods_spu.goods_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * 商品简称 <p/>
     * This method returns the value of the database column tb_goods_spu.short_name
     *
     * @return the value of tb_goods_spu.short_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * 商品简称 <p/>
     * This method sets the value of the database column tb_goods_spu.short_name
     *
     * @param shortName the value for tb_goods_spu.short_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * 条形码 <p/>
     * This method returns the value of the database column tb_goods_spu.barcode
     *
     * @return the value of tb_goods_spu.barcode
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * 条形码 <p/>
     * This method sets the value of the database column tb_goods_spu.barcode
     *
     * @param barcode the value for tb_goods_spu.barcode
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * 商品图片 <p/>
     * This method returns the value of the database column tb_goods_spu.pic_path
     *
     * @return the value of tb_goods_spu.pic_path
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * 商品图片 <p/>
     * This method sets the value of the database column tb_goods_spu.pic_path
     *
     * @param picPath the value for tb_goods_spu.pic_path
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }

    /**
     * 商品SPU(外部系统) <p/>
     * This method returns the value of the database column tb_goods_spu.goods_out_spu
     *
     * @return the value of tb_goods_spu.goods_out_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getGoodsOutSpu() {
        return goodsOutSpu;
    }

    /**
     * 商品SPU(外部系统) <p/>
     * This method sets the value of the database column tb_goods_spu.goods_out_spu
     *
     * @param goodsOutSpu the value for tb_goods_spu.goods_out_spu
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setGoodsOutSpu(String goodsOutSpu) {
        this.goodsOutSpu = goodsOutSpu == null ? null : goodsOutSpu.trim();
    }

    /**
     * 商品类目 <p/>
     * This method returns the value of the database column tb_goods_spu.cat_id
     *
     * @return the value of tb_goods_spu.cat_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getCatId() {
        return catId;
    }

    /**
     * 商品类目 <p/>
     * This method sets the value of the database column tb_goods_spu.cat_id
     *
     * @param catId the value for tb_goods_spu.cat_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCatId(String catId) {
        this.catId = catId == null ? null : catId.trim();
    }

    /**
     * 商品品牌 <p/>
     * This method returns the value of the database column tb_goods_spu.brand
     *
     * @return the value of tb_goods_spu.brand
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getBrand() {
        return brand;
    }

    /**
     * 商品品牌 <p/>
     * This method sets the value of the database column tb_goods_spu.brand
     *
     * @param brand the value for tb_goods_spu.brand
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setBrand(String brand) {
        this.brand = brand == null ? null : brand.trim();
    }

    /**
     * 商品属性 <p/>
     * This method returns the value of the database column tb_goods_spu.props_name
     *
     * @return the value of tb_goods_spu.props_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getPropsName() {
        return propsName;
    }

    /**
     * 商品属性 <p/>
     * This method sets the value of the database column tb_goods_spu.props_name
     *
     * @param propsName the value for tb_goods_spu.props_name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setPropsName(String propsName) {
        this.propsName = propsName == null ? null : propsName.trim();
    }

    /**
     * 商品属性别名 <p/>
     * This method returns the value of the database column tb_goods_spu.props_alias
     *
     * @return the value of tb_goods_spu.props_alias
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getPropsAlias() {
        return propsAlias;
    }

    /**
     * 商品属性别名 <p/>
     * This method sets the value of the database column tb_goods_spu.props_alias
     *
     * @param propsAlias the value for tb_goods_spu.props_alias
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setPropsAlias(String propsAlias) {
        this.propsAlias = propsAlias == null ? null : propsAlias.trim();
    }

    /**
     * 销售属性 <p/>
     * This method returns the value of the database column tb_goods_spu.sale_props
     *
     * @return the value of tb_goods_spu.sale_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getSaleProps() {
        return saleProps;
    }

    /**
     * 销售属性 <p/>
     * This method sets the value of the database column tb_goods_spu.sale_props
     *
     * @param saleProps the value for tb_goods_spu.sale_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setSaleProps(String saleProps) {
        this.saleProps = saleProps == null ? null : saleProps.trim();
    }

    /**
     * 商品属性(非关键) <p/>
     * This method returns the value of the database column tb_goods_spu.binds_props
     *
     * @return the value of tb_goods_spu.binds_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getBindsProps() {
        return bindsProps;
    }

    /**
     * 商品属性(非关键) <p/>
     * This method sets the value of the database column tb_goods_spu.binds_props
     *
     * @param bindsProps the value for tb_goods_spu.binds_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setBindsProps(String bindsProps) {
        this.bindsProps = bindsProps == null ? null : bindsProps.trim();
    }

    /**
     * 商品属性(用户自定义) <p/>
     * This method returns the value of the database column tb_goods_spu.customer_props
     *
     * @return the value of tb_goods_spu.customer_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getCustomerProps() {
        return customerProps;
    }

    /**
     * 商品属性(用户自定义) <p/>
     * This method sets the value of the database column tb_goods_spu.customer_props
     *
     * @param customerProps the value for tb_goods_spu.customer_props
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCustomerProps(String customerProps) {
        this.customerProps = customerProps == null ? null : customerProps.trim();
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method returns the value of the database column tb_goods_spu.status
     *
     * @return the value of tb_goods_spu.status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * 当前状态(0 未确认 1 商家确认 2 小二确认  -1 屏蔽  -2 删除) <p/>
     * This method sets the value of the database column tb_goods_spu.status
     *
     * @param status the value for tb_goods_spu.status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 是否在线销售 0否 1是 <p/>
     * This method returns the value of the database column tb_goods_spu.on_sale
     *
     * @return the value of tb_goods_spu.on_sale
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Byte getOnSale() {
        return onSale;
    }

    /**
     * 是否在线销售 0否 1是 <p/>
     * This method sets the value of the database column tb_goods_spu.on_sale
     *
     * @param onSale the value for tb_goods_spu.on_sale
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setOnSale(Byte onSale) {
        this.onSale = onSale;
    }

    /**
     * 平台信息 <p/>
     * This method returns the value of the database column tb_goods_spu.platform
     *
     * @return the value of tb_goods_spu.platform
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * 平台信息 <p/>
     * This method sets the value of the database column tb_goods_spu.platform
     *
     * @param platform the value for tb_goods_spu.platform
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * 备注 <p/>
     * This method returns the value of the database column tb_goods_spu.remark
     *
     * @return the value of tb_goods_spu.remark
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注 <p/>
     * This method sets the value of the database column tb_goods_spu.remark
     *
     * @param remark the value for tb_goods_spu.remark
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.created
     *
     * @return the value of tb_goods_spu.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.created
     *
     * @param created the value for tb_goods_spu.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.modified
     *
     * @return the value of tb_goods_spu.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.modified
     *
     * @param modified the value for tb_goods_spu.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods_spu.enable_status
     *
     * @return the value of tb_goods_spu.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods_spu.enable_status
     *
     * @param enableStatus the value for tb_goods_spu.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}