package com.gcloud.goods.domain;

import java.util.Date;

public class Trade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.sid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.taobao_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long taobaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.tid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.num
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.num_iid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long numIid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.title
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.price
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerCodFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.discount_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String discountFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Integer pointFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.has_post_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean hasPostFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.total_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_lgtype
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isLgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_brand_sale
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isBrandSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_force_wlb
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isForceWlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.created
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.pay_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.modified
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.end_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_message
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String buyerMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.alipay_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long alipayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String alipayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_nick
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String buyerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_area
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String buyerArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_email
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String buyerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.has_yfx
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean hasYfx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.yfx_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String yfxFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.yfx_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String yfxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.shipping_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String shippingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String buyerCodFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.express_agency_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String expressAgencyFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.adjust_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String adjustFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_obtain_point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long buyerObtainPointFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String codFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.trade_from
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String tradeFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.cod_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String codStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.can_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean canRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.commission_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String commissionFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.trade_memo
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String tradeMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_nick
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.payment
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean sellerRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean buyerRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.real_point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long realPointFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.post_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String postFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.buyer_alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String buyerAlipayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_memo
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_flag
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Byte sellerFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_state
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_city
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_district
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_address
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_zip
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_mobile
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.receiver_phone
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receiverPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.consign_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date consignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerAlipayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_mobile
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_phone
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.seller_email
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String sellerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.available_confirm_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String availableConfirmFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.received_payment
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String receivedPayment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.out_sid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String outSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.timeout_action_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date timeoutActionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.promotion
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String promotion;

    /**
     * 分阶段付款的订单状态（例如万人团订单等），目前有三返回状态 FRONT_NOPAID_FINAL_NOPAID(定金未付尾款未付)，FRONT_PAID_FINAL_NOPAID(定金已付尾款未付)，FRONT_PAID_FINAL_PAID(定金和尾款都付) <p/>
     * This field corresponds to the database column tb_trade.step_trade_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String stepTradeStatus;

    /**
     * 分阶段付款的已付金额（万人团订单已付金额） <p/>
     * This field corresponds to the database column tb_trade.step_paid_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long stepPaidFee;

    /**
     * 数据库最后更新时间 <p/>
     * This field corresponds to the database column tb_trade.upd_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.merge_split_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Integer mergeSplitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.sys_tid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long sysTid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.yd_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String ydId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.enable_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean enableStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.can_confirm_send
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean canConfirmSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.express_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date expressPrintTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.deliver_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date deliverPrintTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.assembly_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Date assemblyPrintTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.check_manual_merge_count
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Integer checkManualMergeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.template_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.template_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_stockout
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isStockout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_excep
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isExcep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_halt
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isHalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_verify
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isVerify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.is_refund
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean isRefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.can_delivered
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private Boolean canDelivered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.invoice_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String invoiceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.invoice_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.invoice_kind
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String invoiceKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trade.gift_item_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    private String giftItemName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.id
     *
     * @return the value of tb_trade.id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.id
     *
     * @param id the value for tb_trade.id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.sid
     *
     * @return the value of tb_trade.sid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.sid
     *
     * @param sid the value for tb_trade.sid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.taobao_id
     *
     * @return the value of tb_trade.taobao_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getTaobaoId() {
        return taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.taobao_id
     *
     * @param taobaoId the value for tb_trade.taobao_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTaobaoId(Long taobaoId) {
        this.taobaoId = taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.tid
     *
     * @return the value of tb_trade.tid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.tid
     *
     * @param tid the value for tb_trade.tid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.num
     *
     * @return the value of tb_trade.num
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.num
     *
     * @param num the value for tb_trade.num
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.num_iid
     *
     * @return the value of tb_trade.num_iid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.num_iid
     *
     * @param numIid the value for tb_trade.num_iid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.status
     *
     * @return the value of tb_trade.status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.status
     *
     * @param status the value for tb_trade.status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.type
     *
     * @return the value of tb_trade.type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.type
     *
     * @param type the value for tb_trade.type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.title
     *
     * @return the value of tb_trade.title
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.title
     *
     * @param title the value for tb_trade.title
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.price
     *
     * @return the value of tb_trade.price
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.price
     *
     * @param price the value for tb_trade.price
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_cod_fee
     *
     * @return the value of tb_trade.seller_cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerCodFee() {
        return sellerCodFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_cod_fee
     *
     * @param sellerCodFee the value for tb_trade.seller_cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerCodFee(String sellerCodFee) {
        this.sellerCodFee = sellerCodFee == null ? null : sellerCodFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.discount_fee
     *
     * @return the value of tb_trade.discount_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getDiscountFee() {
        return discountFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.discount_fee
     *
     * @param discountFee the value for tb_trade.discount_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setDiscountFee(String discountFee) {
        this.discountFee = discountFee == null ? null : discountFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.point_fee
     *
     * @return the value of tb_trade.point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Integer getPointFee() {
        return pointFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.point_fee
     *
     * @param pointFee the value for tb_trade.point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setPointFee(Integer pointFee) {
        this.pointFee = pointFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.has_post_fee
     *
     * @return the value of tb_trade.has_post_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getHasPostFee() {
        return hasPostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.has_post_fee
     *
     * @param hasPostFee the value for tb_trade.has_post_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setHasPostFee(Boolean hasPostFee) {
        this.hasPostFee = hasPostFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.total_fee
     *
     * @return the value of tb_trade.total_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.total_fee
     *
     * @param totalFee the value for tb_trade.total_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTotalFee(String totalFee) {
        this.totalFee = totalFee == null ? null : totalFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_lgtype
     *
     * @return the value of tb_trade.is_lgtype
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsLgtype() {
        return isLgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_lgtype
     *
     * @param isLgtype the value for tb_trade.is_lgtype
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsLgtype(Boolean isLgtype) {
        this.isLgtype = isLgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_brand_sale
     *
     * @return the value of tb_trade.is_brand_sale
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsBrandSale() {
        return isBrandSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_brand_sale
     *
     * @param isBrandSale the value for tb_trade.is_brand_sale
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsBrandSale(Boolean isBrandSale) {
        this.isBrandSale = isBrandSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_force_wlb
     *
     * @return the value of tb_trade.is_force_wlb
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsForceWlb() {
        return isForceWlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_force_wlb
     *
     * @param isForceWlb the value for tb_trade.is_force_wlb
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsForceWlb(Boolean isForceWlb) {
        this.isForceWlb = isForceWlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.created
     *
     * @return the value of tb_trade.created
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.created
     *
     * @param created the value for tb_trade.created
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.pay_time
     *
     * @return the value of tb_trade.pay_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.pay_time
     *
     * @param payTime the value for tb_trade.pay_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.modified
     *
     * @return the value of tb_trade.modified
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.modified
     *
     * @param modified the value for tb_trade.modified
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.end_time
     *
     * @return the value of tb_trade.end_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.end_time
     *
     * @param endTime the value for tb_trade.end_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_message
     *
     * @return the value of tb_trade.buyer_message
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getBuyerMessage() {
        return buyerMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_message
     *
     * @param buyerMessage the value for tb_trade.buyer_message
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerMessage(String buyerMessage) {
        this.buyerMessage = buyerMessage == null ? null : buyerMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.alipay_id
     *
     * @return the value of tb_trade.alipay_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getAlipayId() {
        return alipayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.alipay_id
     *
     * @param alipayId the value for tb_trade.alipay_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setAlipayId(Long alipayId) {
        this.alipayId = alipayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.alipay_no
     *
     * @return the value of tb_trade.alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getAlipayNo() {
        return alipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.alipay_no
     *
     * @param alipayNo the value for tb_trade.alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setAlipayNo(String alipayNo) {
        this.alipayNo = alipayNo == null ? null : alipayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_nick
     *
     * @return the value of tb_trade.buyer_nick
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getBuyerNick() {
        return buyerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_nick
     *
     * @param buyerNick the value for tb_trade.buyer_nick
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerNick(String buyerNick) {
        this.buyerNick = buyerNick == null ? null : buyerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_area
     *
     * @return the value of tb_trade.buyer_area
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getBuyerArea() {
        return buyerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_area
     *
     * @param buyerArea the value for tb_trade.buyer_area
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerArea(String buyerArea) {
        this.buyerArea = buyerArea == null ? null : buyerArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_email
     *
     * @return the value of tb_trade.buyer_email
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_email
     *
     * @param buyerEmail the value for tb_trade.buyer_email
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.has_yfx
     *
     * @return the value of tb_trade.has_yfx
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getHasYfx() {
        return hasYfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.has_yfx
     *
     * @param hasYfx the value for tb_trade.has_yfx
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setHasYfx(Boolean hasYfx) {
        this.hasYfx = hasYfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.yfx_fee
     *
     * @return the value of tb_trade.yfx_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getYfxFee() {
        return yfxFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.yfx_fee
     *
     * @param yfxFee the value for tb_trade.yfx_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setYfxFee(String yfxFee) {
        this.yfxFee = yfxFee == null ? null : yfxFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.yfx_id
     *
     * @return the value of tb_trade.yfx_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getYfxId() {
        return yfxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.yfx_id
     *
     * @param yfxId the value for tb_trade.yfx_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setYfxId(String yfxId) {
        this.yfxId = yfxId == null ? null : yfxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.shipping_type
     *
     * @return the value of tb_trade.shipping_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.shipping_type
     *
     * @param shippingType the value for tb_trade.shipping_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setShippingType(String shippingType) {
        this.shippingType = shippingType == null ? null : shippingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_cod_fee
     *
     * @return the value of tb_trade.buyer_cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getBuyerCodFee() {
        return buyerCodFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_cod_fee
     *
     * @param buyerCodFee the value for tb_trade.buyer_cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerCodFee(String buyerCodFee) {
        this.buyerCodFee = buyerCodFee == null ? null : buyerCodFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.express_agency_fee
     *
     * @return the value of tb_trade.express_agency_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getExpressAgencyFee() {
        return expressAgencyFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.express_agency_fee
     *
     * @param expressAgencyFee the value for tb_trade.express_agency_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setExpressAgencyFee(String expressAgencyFee) {
        this.expressAgencyFee = expressAgencyFee == null ? null : expressAgencyFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.adjust_fee
     *
     * @return the value of tb_trade.adjust_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getAdjustFee() {
        return adjustFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.adjust_fee
     *
     * @param adjustFee the value for tb_trade.adjust_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setAdjustFee(String adjustFee) {
        this.adjustFee = adjustFee == null ? null : adjustFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_obtain_point_fee
     *
     * @return the value of tb_trade.buyer_obtain_point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getBuyerObtainPointFee() {
        return buyerObtainPointFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_obtain_point_fee
     *
     * @param buyerObtainPointFee the value for tb_trade.buyer_obtain_point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerObtainPointFee(Long buyerObtainPointFee) {
        this.buyerObtainPointFee = buyerObtainPointFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.cod_fee
     *
     * @return the value of tb_trade.cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getCodFee() {
        return codFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.cod_fee
     *
     * @param codFee the value for tb_trade.cod_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCodFee(String codFee) {
        this.codFee = codFee == null ? null : codFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.trade_from
     *
     * @return the value of tb_trade.trade_from
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getTradeFrom() {
        return tradeFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.trade_from
     *
     * @param tradeFrom the value for tb_trade.trade_from
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTradeFrom(String tradeFrom) {
        this.tradeFrom = tradeFrom == null ? null : tradeFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.cod_status
     *
     * @return the value of tb_trade.cod_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getCodStatus() {
        return codStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.cod_status
     *
     * @param codStatus the value for tb_trade.cod_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCodStatus(String codStatus) {
        this.codStatus = codStatus == null ? null : codStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.can_rate
     *
     * @return the value of tb_trade.can_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getCanRate() {
        return canRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.can_rate
     *
     * @param canRate the value for tb_trade.can_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCanRate(Boolean canRate) {
        this.canRate = canRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.commission_fee
     *
     * @return the value of tb_trade.commission_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getCommissionFee() {
        return commissionFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.commission_fee
     *
     * @param commissionFee the value for tb_trade.commission_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCommissionFee(String commissionFee) {
        this.commissionFee = commissionFee == null ? null : commissionFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.trade_memo
     *
     * @return the value of tb_trade.trade_memo
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getTradeMemo() {
        return tradeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.trade_memo
     *
     * @param tradeMemo the value for tb_trade.trade_memo
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTradeMemo(String tradeMemo) {
        this.tradeMemo = tradeMemo == null ? null : tradeMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_nick
     *
     * @return the value of tb_trade.seller_nick
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerNick() {
        return sellerNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_nick
     *
     * @param sellerNick the value for tb_trade.seller_nick
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerNick(String sellerNick) {
        this.sellerNick = sellerNick == null ? null : sellerNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.payment
     *
     * @return the value of tb_trade.payment
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.payment
     *
     * @param payment the value for tb_trade.payment
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_rate
     *
     * @return the value of tb_trade.seller_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getSellerRate() {
        return sellerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_rate
     *
     * @param sellerRate the value for tb_trade.seller_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerRate(Boolean sellerRate) {
        this.sellerRate = sellerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_rate
     *
     * @return the value of tb_trade.buyer_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getBuyerRate() {
        return buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_rate
     *
     * @param buyerRate the value for tb_trade.buyer_rate
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerRate(Boolean buyerRate) {
        this.buyerRate = buyerRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.real_point_fee
     *
     * @return the value of tb_trade.real_point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getRealPointFee() {
        return realPointFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.real_point_fee
     *
     * @param realPointFee the value for tb_trade.real_point_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setRealPointFee(Long realPointFee) {
        this.realPointFee = realPointFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.post_fee
     *
     * @return the value of tb_trade.post_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.post_fee
     *
     * @param postFee the value for tb_trade.post_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setPostFee(String postFee) {
        this.postFee = postFee == null ? null : postFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.buyer_alipay_no
     *
     * @return the value of tb_trade.buyer_alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getBuyerAlipayNo() {
        return buyerAlipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.buyer_alipay_no
     *
     * @param buyerAlipayNo the value for tb_trade.buyer_alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setBuyerAlipayNo(String buyerAlipayNo) {
        this.buyerAlipayNo = buyerAlipayNo == null ? null : buyerAlipayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_memo
     *
     * @return the value of tb_trade.seller_memo
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerMemo() {
        return sellerMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_memo
     *
     * @param sellerMemo the value for tb_trade.seller_memo
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerMemo(String sellerMemo) {
        this.sellerMemo = sellerMemo == null ? null : sellerMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_flag
     *
     * @return the value of tb_trade.seller_flag
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Byte getSellerFlag() {
        return sellerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_flag
     *
     * @param sellerFlag the value for tb_trade.seller_flag
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerFlag(Byte sellerFlag) {
        this.sellerFlag = sellerFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_name
     *
     * @return the value of tb_trade.receiver_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_name
     *
     * @param receiverName the value for tb_trade.receiver_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_state
     *
     * @return the value of tb_trade.receiver_state
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverState() {
        return receiverState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_state
     *
     * @param receiverState the value for tb_trade.receiver_state
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverState(String receiverState) {
        this.receiverState = receiverState == null ? null : receiverState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_city
     *
     * @return the value of tb_trade.receiver_city
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_city
     *
     * @param receiverCity the value for tb_trade.receiver_city
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_district
     *
     * @return the value of tb_trade.receiver_district
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_district
     *
     * @param receiverDistrict the value for tb_trade.receiver_district
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_address
     *
     * @return the value of tb_trade.receiver_address
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_address
     *
     * @param receiverAddress the value for tb_trade.receiver_address
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_zip
     *
     * @return the value of tb_trade.receiver_zip
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_zip
     *
     * @param receiverZip the value for tb_trade.receiver_zip
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_mobile
     *
     * @return the value of tb_trade.receiver_mobile
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_mobile
     *
     * @param receiverMobile the value for tb_trade.receiver_mobile
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.receiver_phone
     *
     * @return the value of tb_trade.receiver_phone
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.receiver_phone
     *
     * @param receiverPhone the value for tb_trade.receiver_phone
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.consign_time
     *
     * @return the value of tb_trade.consign_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getConsignTime() {
        return consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.consign_time
     *
     * @param consignTime the value for tb_trade.consign_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setConsignTime(Date consignTime) {
        this.consignTime = consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_alipay_no
     *
     * @return the value of tb_trade.seller_alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerAlipayNo() {
        return sellerAlipayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_alipay_no
     *
     * @param sellerAlipayNo the value for tb_trade.seller_alipay_no
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerAlipayNo(String sellerAlipayNo) {
        this.sellerAlipayNo = sellerAlipayNo == null ? null : sellerAlipayNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_mobile
     *
     * @return the value of tb_trade.seller_mobile
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerMobile() {
        return sellerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_mobile
     *
     * @param sellerMobile the value for tb_trade.seller_mobile
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerMobile(String sellerMobile) {
        this.sellerMobile = sellerMobile == null ? null : sellerMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_phone
     *
     * @return the value of tb_trade.seller_phone
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerPhone() {
        return sellerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_phone
     *
     * @param sellerPhone the value for tb_trade.seller_phone
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerPhone(String sellerPhone) {
        this.sellerPhone = sellerPhone == null ? null : sellerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_name
     *
     * @return the value of tb_trade.seller_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_name
     *
     * @param sellerName the value for tb_trade.seller_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.seller_email
     *
     * @return the value of tb_trade.seller_email
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getSellerEmail() {
        return sellerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.seller_email
     *
     * @param sellerEmail the value for tb_trade.seller_email
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSellerEmail(String sellerEmail) {
        this.sellerEmail = sellerEmail == null ? null : sellerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.available_confirm_fee
     *
     * @return the value of tb_trade.available_confirm_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getAvailableConfirmFee() {
        return availableConfirmFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.available_confirm_fee
     *
     * @param availableConfirmFee the value for tb_trade.available_confirm_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setAvailableConfirmFee(String availableConfirmFee) {
        this.availableConfirmFee = availableConfirmFee == null ? null : availableConfirmFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.received_payment
     *
     * @return the value of tb_trade.received_payment
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getReceivedPayment() {
        return receivedPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.received_payment
     *
     * @param receivedPayment the value for tb_trade.received_payment
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setReceivedPayment(String receivedPayment) {
        this.receivedPayment = receivedPayment == null ? null : receivedPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.out_sid
     *
     * @return the value of tb_trade.out_sid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getOutSid() {
        return outSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.out_sid
     *
     * @param outSid the value for tb_trade.out_sid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setOutSid(String outSid) {
        this.outSid = outSid == null ? null : outSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.timeout_action_time
     *
     * @return the value of tb_trade.timeout_action_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getTimeoutActionTime() {
        return timeoutActionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.timeout_action_time
     *
     * @param timeoutActionTime the value for tb_trade.timeout_action_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTimeoutActionTime(Date timeoutActionTime) {
        this.timeoutActionTime = timeoutActionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.promotion
     *
     * @return the value of tb_trade.promotion
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getPromotion() {
        return promotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.promotion
     *
     * @param promotion the value for tb_trade.promotion
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setPromotion(String promotion) {
        this.promotion = promotion == null ? null : promotion.trim();
    }

    /**
     * 分阶段付款的订单状态（例如万人团订单等），目前有三返回状态 FRONT_NOPAID_FINAL_NOPAID(定金未付尾款未付)，FRONT_PAID_FINAL_NOPAID(定金已付尾款未付)，FRONT_PAID_FINAL_PAID(定金和尾款都付) <p/>
     * This method returns the value of the database column tb_trade.step_trade_status
     *
     * @return the value of tb_trade.step_trade_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getStepTradeStatus() {
        return stepTradeStatus;
    }

    /**
     * 分阶段付款的订单状态（例如万人团订单等），目前有三返回状态 FRONT_NOPAID_FINAL_NOPAID(定金未付尾款未付)，FRONT_PAID_FINAL_NOPAID(定金已付尾款未付)，FRONT_PAID_FINAL_PAID(定金和尾款都付) <p/>
     * This method sets the value of the database column tb_trade.step_trade_status
     *
     * @param stepTradeStatus the value for tb_trade.step_trade_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setStepTradeStatus(String stepTradeStatus) {
        this.stepTradeStatus = stepTradeStatus == null ? null : stepTradeStatus.trim();
    }

    /**
     * 分阶段付款的已付金额（万人团订单已付金额） <p/>
     * This method returns the value of the database column tb_trade.step_paid_fee
     *
     * @return the value of tb_trade.step_paid_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getStepPaidFee() {
        return stepPaidFee;
    }

    /**
     * 分阶段付款的已付金额（万人团订单已付金额） <p/>
     * This method sets the value of the database column tb_trade.step_paid_fee
     *
     * @param stepPaidFee the value for tb_trade.step_paid_fee
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setStepPaidFee(Long stepPaidFee) {
        this.stepPaidFee = stepPaidFee;
    }

    /**
     * 数据库最后更新时间 <p/>
     * This method returns the value of the database column tb_trade.upd_time
     *
     * @return the value of tb_trade.upd_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * 数据库最后更新时间 <p/>
     * This method sets the value of the database column tb_trade.upd_time
     *
     * @param updTime the value for tb_trade.upd_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.merge_split_type
     *
     * @return the value of tb_trade.merge_split_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Integer getMergeSplitType() {
        return mergeSplitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.merge_split_type
     *
     * @param mergeSplitType the value for tb_trade.merge_split_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setMergeSplitType(Integer mergeSplitType) {
        this.mergeSplitType = mergeSplitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.sys_tid
     *
     * @return the value of tb_trade.sys_tid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getSysTid() {
        return sysTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.sys_tid
     *
     * @param sysTid the value for tb_trade.sys_tid
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setSysTid(Long sysTid) {
        this.sysTid = sysTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.yd_id
     *
     * @return the value of tb_trade.yd_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getYdId() {
        return ydId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.yd_id
     *
     * @param ydId the value for tb_trade.yd_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setYdId(String ydId) {
        this.ydId = ydId == null ? null : ydId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.enable_status
     *
     * @return the value of tb_trade.enable_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.enable_status
     *
     * @param enableStatus the value for tb_trade.enable_status
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.can_confirm_send
     *
     * @return the value of tb_trade.can_confirm_send
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getCanConfirmSend() {
        return canConfirmSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.can_confirm_send
     *
     * @param canConfirmSend the value for tb_trade.can_confirm_send
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCanConfirmSend(Boolean canConfirmSend) {
        this.canConfirmSend = canConfirmSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.express_print_time
     *
     * @return the value of tb_trade.express_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getExpressPrintTime() {
        return expressPrintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.express_print_time
     *
     * @param expressPrintTime the value for tb_trade.express_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setExpressPrintTime(Date expressPrintTime) {
        this.expressPrintTime = expressPrintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.deliver_print_time
     *
     * @return the value of tb_trade.deliver_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getDeliverPrintTime() {
        return deliverPrintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.deliver_print_time
     *
     * @param deliverPrintTime the value for tb_trade.deliver_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setDeliverPrintTime(Date deliverPrintTime) {
        this.deliverPrintTime = deliverPrintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.assembly_print_time
     *
     * @return the value of tb_trade.assembly_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Date getAssemblyPrintTime() {
        return assemblyPrintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.assembly_print_time
     *
     * @param assemblyPrintTime the value for tb_trade.assembly_print_time
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setAssemblyPrintTime(Date assemblyPrintTime) {
        this.assemblyPrintTime = assemblyPrintTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.check_manual_merge_count
     *
     * @return the value of tb_trade.check_manual_merge_count
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Integer getCheckManualMergeCount() {
        return checkManualMergeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.check_manual_merge_count
     *
     * @param checkManualMergeCount the value for tb_trade.check_manual_merge_count
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCheckManualMergeCount(Integer checkManualMergeCount) {
        this.checkManualMergeCount = checkManualMergeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.template_id
     *
     * @return the value of tb_trade.template_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.template_id
     *
     * @param templateId the value for tb_trade.template_id
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.template_type
     *
     * @return the value of tb_trade.template_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.template_type
     *
     * @param templateType the value for tb_trade.template_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setTemplateType(Boolean templateType) {
        this.templateType = templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_stockout
     *
     * @return the value of tb_trade.is_stockout
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsStockout() {
        return isStockout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_stockout
     *
     * @param isStockout the value for tb_trade.is_stockout
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsStockout(Boolean isStockout) {
        this.isStockout = isStockout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_excep
     *
     * @return the value of tb_trade.is_excep
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsExcep() {
        return isExcep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_excep
     *
     * @param isExcep the value for tb_trade.is_excep
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsExcep(Boolean isExcep) {
        this.isExcep = isExcep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_halt
     *
     * @return the value of tb_trade.is_halt
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsHalt() {
        return isHalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_halt
     *
     * @param isHalt the value for tb_trade.is_halt
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsHalt(Boolean isHalt) {
        this.isHalt = isHalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_verify
     *
     * @return the value of tb_trade.is_verify
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsVerify() {
        return isVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_verify
     *
     * @param isVerify the value for tb_trade.is_verify
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsVerify(Boolean isVerify) {
        this.isVerify = isVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.is_refund
     *
     * @return the value of tb_trade.is_refund
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getIsRefund() {
        return isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.is_refund
     *
     * @param isRefund the value for tb_trade.is_refund
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setIsRefund(Boolean isRefund) {
        this.isRefund = isRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.can_delivered
     *
     * @return the value of tb_trade.can_delivered
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public Boolean getCanDelivered() {
        return canDelivered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.can_delivered
     *
     * @param canDelivered the value for tb_trade.can_delivered
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setCanDelivered(Boolean canDelivered) {
        this.canDelivered = canDelivered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.invoice_name
     *
     * @return the value of tb_trade.invoice_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getInvoiceName() {
        return invoiceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.invoice_name
     *
     * @param invoiceName the value for tb_trade.invoice_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setInvoiceName(String invoiceName) {
        this.invoiceName = invoiceName == null ? null : invoiceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.invoice_type
     *
     * @return the value of tb_trade.invoice_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.invoice_type
     *
     * @param invoiceType the value for tb_trade.invoice_type
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType == null ? null : invoiceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.invoice_kind
     *
     * @return the value of tb_trade.invoice_kind
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getInvoiceKind() {
        return invoiceKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.invoice_kind
     *
     * @param invoiceKind the value for tb_trade.invoice_kind
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setInvoiceKind(String invoiceKind) {
        this.invoiceKind = invoiceKind == null ? null : invoiceKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trade.gift_item_name
     *
     * @return the value of tb_trade.gift_item_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public String getGiftItemName() {
        return giftItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trade.gift_item_name
     *
     * @param giftItemName the value for tb_trade.gift_item_name
     *
     * @mbggenerated Thu Aug 11 16:43:39 CST 2016
     */
    public void setGiftItemName(String giftItemName) {
        this.giftItemName = giftItemName == null ? null : giftItemName.trim();
    }
}