package com.gcloud.goods.domain;

import java.util.Date;

public class Warehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long id;

    /**
     * 公司ID <p/>
     * This field corresponds to the database column tb_warehouse.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long companyId;

    /**
     * 门店ID <p/>
     * This field corresponds to the database column tb_warehouse.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long storeId;

    /**
     * 仓库ID <p/>
     * This field corresponds to the database column tb_warehouse.warehouse_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Long warehouseId;

    /**
     * 默认仓储 <p/>
     * This field corresponds to the database column tb_warehouse.name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String name;

    /**
     * 仓库地址 <p/>
     * This field corresponds to the database column tb_warehouse.address
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String address;

    /**
     * 高德地址（经纬度） <p/>
     * This field corresponds to the database column tb_warehouse.location
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Date modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_warehouse.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    private Boolean enableStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse.id
     *
     * @return the value of tb_warehouse.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse.id
     *
     * @param id the value for tb_warehouse.id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 公司ID <p/>
     * This method returns the value of the database column tb_warehouse.company_id
     *
     * @return the value of tb_warehouse.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * 公司ID <p/>
     * This method sets the value of the database column tb_warehouse.company_id
     *
     * @param companyId the value for tb_warehouse.company_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 门店ID <p/>
     * This method returns the value of the database column tb_warehouse.store_id
     *
     * @return the value of tb_warehouse.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * 门店ID <p/>
     * This method sets the value of the database column tb_warehouse.store_id
     *
     * @param storeId the value for tb_warehouse.store_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * 仓库ID <p/>
     * This method returns the value of the database column tb_warehouse.warehouse_id
     *
     * @return the value of tb_warehouse.warehouse_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Long getWarehouseId() {
        return warehouseId;
    }

    /**
     * 仓库ID <p/>
     * This method sets the value of the database column tb_warehouse.warehouse_id
     *
     * @param warehouseId the value for tb_warehouse.warehouse_id
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setWarehouseId(Long warehouseId) {
        this.warehouseId = warehouseId;
    }

    /**
     * 默认仓储 <p/>
     * This method returns the value of the database column tb_warehouse.name
     *
     * @return the value of tb_warehouse.name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * 默认仓储 <p/>
     * This method sets the value of the database column tb_warehouse.name
     *
     * @param name the value for tb_warehouse.name
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 仓库地址 <p/>
     * This method returns the value of the database column tb_warehouse.address
     *
     * @return the value of tb_warehouse.address
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * 仓库地址 <p/>
     * This method sets the value of the database column tb_warehouse.address
     *
     * @param address the value for tb_warehouse.address
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 高德地址（经纬度） <p/>
     * This method returns the value of the database column tb_warehouse.location
     *
     * @return the value of tb_warehouse.location
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public String getLocation() {
        return location;
    }

    /**
     * 高德地址（经纬度） <p/>
     * This method sets the value of the database column tb_warehouse.location
     *
     * @param location the value for tb_warehouse.location
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse.created
     *
     * @return the value of tb_warehouse.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse.created
     *
     * @param created the value for tb_warehouse.created
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse.modified
     *
     * @return the value of tb_warehouse.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse.modified
     *
     * @param modified the value for tb_warehouse.modified
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_warehouse.enable_status
     *
     * @return the value of tb_warehouse.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public Boolean getEnableStatus() {
        return enableStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_warehouse.enable_status
     *
     * @param enableStatus the value for tb_warehouse.enable_status
     *
     * @mbggenerated Sat Aug 13 22:53:42 CST 2016
     */
    public void setEnableStatus(Boolean enableStatus) {
        this.enableStatus = enableStatus;
    }
}