<settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">

	<localRepository>D:/Program Files/repository-home</localRepository>
	<mirrors>
		<mirror>
		  <id>CN</id>
		  <name>OSChina Central</name>                                                                                                                       
		  <url>http://maven.oschina.net/content/groups/public/</url>
		  <mirrorOf>central</mirrorOf>
		</mirror>

		<mirror>
		  <id>CN</id>
		  <name>maven.net</name>
		  <id>plugin-repo-mirror</id>
		  <url>http://maven.net.cn/content/groups/public/</url>
		  <mirrorOf>central</mirrorOf>
		</mirror>
	</mirrors>
</settings>